name: "Issue Actions"
on:
  issues:
    types: [opened, edited, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
