name: "Issue Actions"
on:
  issues:
    types: [labeled, edited]

jobs:
  Bender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          patch-branch: "bot-patch"
          administrators: [leplay]
          editors-friends: [nicing]

