name: "Issue Action"
on:
  issues:
    types: [labeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: openquiz/openquiz-actions@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
